import {
    BatteryLabel,
    Bluetooth,
    Cava,
    ClientTitle,
    Clock,
    Cpu,
    CpuTemp,
    Hypridle,
    Hyprsunset,
    KbInput,
    Media,
    Menu,
    Microphone,
    ModuleSeparator,
    Netstat,
    Network,
    Notifications,
    Power,
    Ram,
    Storage,
    Submap,
    SysTray,
    Updates,
    Volume,
    Weather,
    Workspaces,
    WorldClock,
} from '../modules';
import { WidgetContainer } from '../shared/widgetContainer';
import { WidgetFactory } from './WidgetRegistry';

export function getCoreWidgets(): Record<string, WidgetFactory> {
    return {
        battery: () => WidgetContainer(BatteryLabel()),
        dashboard: () => WidgetContainer(Menu()),
        workspaces: (monitor: number) => WidgetContainer(Workspaces(monitor)),
        windowtitle: () => WidgetContainer(ClientTitle()),
        media: () => WidgetContainer(Media()),
        notifications: () => WidgetContainer(Notifications()),
        volume: () => WidgetContainer(Volume()),
        network: () => WidgetContainer(Network()),
        bluetooth: () => WidgetContainer(Bluetooth()),
        clock: () => WidgetContainer(Clock()),
        systray: () => WidgetContainer(SysTray()),
        microphone: () => WidgetContainer(Microphone()),
        ram: () => WidgetContainer(Ram()),
        cpu: () => WidgetContainer(Cpu()),
        cputemp: () => WidgetContainer(CpuTemp()),
        storage: () => WidgetContainer(Storage()),
        netstat: () => WidgetContainer(Netstat()),
        kbinput: () => WidgetContainer(KbInput()),
        updates: () => WidgetContainer(Updates()),
        submap: () => WidgetContainer(Submap()),
        weather: () => WidgetContainer(Weather()),
        power: () => WidgetContainer(Power()),
        hyprsunset: () => WidgetContainer(Hyprsunset()),
        hypridle: () => WidgetContainer(Hypridle()),
        cava: () => WidgetContainer(Cava()),
        worldclock: () => WidgetContainer(WorldClock()),
        separator: () => ModuleSeparator(),
    };
}
