export const substitutes = {
    'transmission-gtk': 'transmission',
    'blueberry.py': 'blueberry',
    Caprine: 'facebook-messenger',
    'com.raggesilver.BlackBox-symbolic': 'terminal-symbolic',
    'org.wezfurlong.wezterm-symbolic': 'terminal-symbolic',
    'audio-headset-bluetooth': 'audio-headphones-symbolic',
    'audio-card-analog-usb': 'audio-speakers-symbolic',
    'audio-card-analog-pci': 'audio-card-symbolic',
    'preferences-system': 'emblem-system-symbolic',
    'com.github.Aylur.ags-symbolic': 'controls-symbolic',
    'com.github.Aylur.ags': 'controls-symbolic',
};

export default {
    missing: 'image-missing-symbolic',
    nix: {
        nix: 'nix-snowflake-symbolic',
    },
    app: {
        terminal: 'terminal-symbolic',
    },
    fallback: {
        executable: 'application-x-executable',
        notification: 'dialog-information-symbolic',
        video: 'video-x-generic-symbolic',
        audio: 'audio-x-generic-symbolic',
    },
    ui: {
        close: 'window-close-symbolic',
        colorpicker: 'color-select-symbolic',
        info: 'info-symbolic',
        link: 'external-link-symbolic',
        lock: 'system-lock-screen-symbolic',
        menu: 'open-menu-symbolic',
        refresh: 'view-refresh-symbolic',
        search: 'system-search-symbolic',
        settings: 'emblem-system-symbolic',
        themes: 'preferences-desktop-theme-symbolic',
        tick: 'object-select-symbolic',
        time: 'hourglass-symbolic',
        toolbars: 'toolbars-symbolic',
        warning: 'dialog-warning-symbolic',
        arrow: {
            right: 'pan-end-symbolic',
            left: 'pan-start-symbolic',
            down: 'pan-down-symbolic',
            up: 'pan-up-symbolic',
        },
    },
    audio: {
        mic: {
            muted: 'microphone-disabled-symbolic',
            low: 'microphone-sensitivity-low-symbolic',
            medium: 'microphone-sensitivity-medium-symbolic',
            high: 'microphone-sensitivity-high-symbolic',
        },
        volume: {
            muted: 'audio-volume-muted-symbolic',
            low: 'audio-volume-low-symbolic',
            medium: 'audio-volume-medium-symbolic',
            high: 'audio-volume-high-symbolic',
            overamplified: 'audio-volume-overamplified-symbolic',
        },
        type: {
            headset: 'audio-headphones-symbolic',
            speaker: 'audio-speakers-symbolic',
            card: 'audio-card-symbolic',
        },
        mixer: 'mixer-symbolic',
    },
    powerprofile: {
        balanced: 'power-profile-balanced-symbolic',
        'power-saver': 'power-profile-power-saver-symbolic',
        performance: 'power-profile-performance-symbolic',
    },
    asusctl: {
        profile: {
            Balanced: 'power-profile-balanced-symbolic',
            Quiet: 'power-profile-power-saver-symbolic',
            Performance: 'power-profile-performance-symbolic',
        },
        mode: {
            Integrated: 'processor-symbolic',
            Hybrid: 'controller-symbolic',
        },
    },
    battery: {
        charging: 'battery-flash-symbolic',
        warning: 'battery-empty-symbolic',
    },
    bluetooth: {
        enabled: 'bluetooth-active-symbolic',
        disabled: 'bluetooth-disabled-symbolic',
    },
    brightness: {
        indicator: 'display-brightness-symbolic',
        keyboard: 'keyboard-brightness-symbolic',
        screen: 'display-brightness-symbolic',
    },
    powermenu: {
        sleep: 'weather-clear-night-symbolic',
        reboot: 'system-reboot-symbolic',
        logout: 'system-log-out-symbolic',
        shutdown: 'system-shutdown-symbolic',
    },
    recorder: {
        recording: 'media-record-symbolic',
    },
    notifications: {
        noisy: 'org.gnome.Settings-notifications-symbolic',
        silent: 'notifications-disabled-symbolic',
        message: 'chat-bubbles-symbolic',
    },
    trash: {
        full: 'user-trash-full-symbolic',
        empty: 'user-trash-symbolic',
    },
    mpris: {
        shuffle: {
            enabled: 'media-playlist-shuffle-symbolic',
            disabled: 'media-playlist-consecutive-symbolic',
        },
        loop: {
            none: 'media-playlist-repeat-symbolic',
            track: 'media-playlist-repeat-song-symbolic',
            playlist: 'media-playlist-repeat-symbolic',
        },
        playing: 'media-playback-pause-symbolic',
        paused: 'media-playback-start-symbolic',
        stopped: 'media-playback-start-symbolic',
        prev: 'media-skip-backward-symbolic',
        next: 'media-skip-forward-symbolic',
    },
    system: {
        cpu: 'org.gnome.SystemMonitor-symbolic',
        ram: 'drive-harddisk-solidstate-symbolic',
        temp: 'temperature-symbolic',
    },
    color: {
        dark: 'dark-mode-symbolic',
        light: 'light-mode-symbolic',
    },
    weather: {
        warning: 'dialog-warning-symbolic',
        sunny: 'weather-clear-symbolic',
        clear: 'weather-clear-night-symbolic',
        partly_cloudy: 'weather-few-clouds-symbolic',
        partly_cloudy_night: 'weather-few-clouds-night-symbolic',
        cloudy: 'weather-overcast-symbolic',
        overcast: 'weather-overcast-symbolic',
        mist: 'weather-overcast-symbolic',
        patchy_rain_nearby: 'weather-showers-scattered-symbolic',
        patchy_rain_possible: 'weather-showers-scattered-symbolic',
        patchy_snow_possible: 'weather-snow-symbolic',
        patchy_sleet_possible: 'weather-snow-symbolic',
        patchy_freezing_drizzle_possible: 'weather-showers-scattered-symbolic',
        thundery_outbreaks_possible: 'weather-overcast-symbolic',
        blowing_snow: 'weather-snow-symbolic',
        blizzard: 'weather-snow-symbolic',
        fog: 'weather-fog-symbolic',
        freezing_fog: 'weather-fog-symbolic',
        patchy_light_drizzle: 'weather-showers-scattered-symbolic',
        light_drizzle: 'weather-showers-symbolic',
        freezing_drizzle: 'weather-showers-symbolic',
        heavy_freezing_drizzle: 'weather-showers-symbolic',
        patchy_light_rain: 'weather-showers-scattered-symbolic',
        light_rain: 'weather-showers-symbolic',
        moderate_rain_at_times: 'weather-showers-symbolic',
        moderate_rain: 'weather-showers-symbolic',
        heavy_rain_at_times: 'weather-showers-symbolic',
        heavy_rain: 'weather-showers-symbolic',
        light_freezing_rain: 'weather-showers-symbolic',
        moderate_or_heavy_freezing_rain: 'weather-showers-symbolic',
        light_sleet: 'weather-snow-symbolic',
        moderate_or_heavy_sleet: 'weather-snow-symbolic',
        patchy_light_snow: 'weather-snow-symbolic',
        light_snow: 'weather-snow-symbolic',
        patchy_moderate_snow: 'weather-snow-symbolic',
        moderate_snow: 'weather-snow-symbolic',
        patchy_heavy_snow: 'weather-snow-symbolic',
        heavy_snow: 'weather-snow-symbolic',
        ice_pellets: 'weather-showers-symbolic',
        light_rain_shower: 'weather-showers-symbolic',
        moderate_or_heavy_rain_shower: 'weather-showers-symbolic',
        torrential_rain_shower: 'weather-showers-symbolic',
        light_sleet_showers: 'weather-showers-symbolic',
        moderate_or_heavy_sleet_showers: 'weather-showers-symbolic',
        light_snow_showers: 'weather-snow-symbolic',
        moderate_or_heavy_snow_showers: 'weather-snow-symbolic',
        light_showers_of_ice_pellets: 'weather-showers-symbolic',
        moderate_or_heavy_showers_of_ice_pellets: 'weather-showers-symbolic',
        patchy_light_rain_with_thunder: 'weather-showers-scattered-symbolic',
        moderate_or_heavy_rain_with_thunder: 'weather-showers-symbolic',
        patchy_light_snow_with_thunder: 'weather-snow-symbolic',
        moderate_or_heavy_snow_with_thunder: 'weather-snow-symbolic',
    },
} as const;
