name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    code_quality:
        runs-on: ubuntu-latest

        container:
            image: fedora:latest

        steps:
            - name: Install Node.js and npm
              run: |
                  dnf install -y nodejs npm aylurs-gtk-shell
                  sudo dnf install -y aylurs-gtk-shell

            - name: Initialize AGS
              run: sudo ags --init

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

            - name: ESLint
              run: npm run lint

            - name: Type Check - Extended Diagnostics
              run: npx tsc --noEmit --pretty --extendedDiagnostics
