name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    code_quality:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main repository with submodules
              uses: actions/checkout@v3
            #   with:
            #       submodules: true
            #
            # - name: Clone astal repository to /usr/share/astal/gjs
            #   run: |
            #       sudo mkdir -p /usr/share/astal/
            #       sudo git clone https://github.com/Jas-SinghFSU/astalgjs.git /usr/share/astal
            #
            # - name: Copy types to @girs/
            #   run: |
            #       rm -rf @girs
            #       mkdir -p @girs
            #       cp -R external/ags-types/@girs/* @girs/
            #       rm -rf external/ags-types

            - name: Node Setup
              uses: actions/setup-node@v3
              with:
                  node-version: '21'

            - name: Install Dependencies
              run: npm install

            - name: ESLint
              run: npm run lint

            # - name: Type Check
            #   run: npx tsc --noEmit --pretty --extendedDiagnostics
