name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    code_quality:
        runs-on: ubuntu-latest

        steps:
            - name: Install Node.js and npm
              run: |
                  sudo dnf install -y nodejs npm

            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Install Node.js Dependencies
              run: npm install

            - name: Run ESLint
              run: npm run lint

            - name: Run Type Check - Extended Diagnostics
              run: npx tsc --noEmit --pretty --extendedDiagnostics
