name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    code_quality:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main repository
              uses: actions/checkout@v3

            - name: Clone ags-types repository
              uses: actions/checkout@v3
              with:
                  repository: Jas-SinghFSU/ags-types
                  path: types

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21'

            - name: Install Dependencies
              run: npm install

            - name: Run ESLint
              run: npm run lint

            - name: Run Type Check - Extended Diagnostics
              run: npx tsc --noEmit --pretty --extendedDiagnostics
