name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    code_quality:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Node Setup
              uses: actions/setup-node@v3
              with:
                  node-version: '21'

            - name: Install dependencies
              run: npm install

            - name: ESLint
              run: npm run lint

            - name: Type Check - Extended Diagnostics
              run: npx tsc --noEmit --pretty --extendedDiagnostics
            # - name: Type Check
            #   run: npx tsc --noEmit -p tsconfig.json
