name: ESLint Debug

on:
  push:
    branches: [ matugen ]

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm ci
      
      - name: Environment information
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "ESLint version: $(npx eslint --version)"
          echo "TypeScript version: $(npx tsc --version)"
          echo "@typescript-eslint/parser version: $(npm list @typescript-eslint/parser)"
          echo "@typescript-eslint/eslint-plugin version: $(npm list @typescript-eslint/eslint-plugin)"
          echo "Current directory: $(pwd)"
          echo "User: $(whoami)"
          echo "OS info: $(uname -a)"
          
      - name: ESLint configuration
        run: |
          echo "ESLint config content:"
          cat .eslintrc.json
          echo "TypeScript config content:"
          cat tsconfig.json
          echo "ESLint resolved config:"
          npx eslint --print-config src/components/menus/media/components/helpers.ts > eslint-resolved-config.json
          cat eslint-resolved-config.json
          
      - name: Test ESLint with different configs
        run: |
          echo "With original config:"
          npx eslint --config .eslintrc.json ./src/components/menus/media/components/helpers.ts || echo "Errors found"
          
          echo "Creating strict test config..."
          echo '{
            "parser": "@typescript-eslint/parser",
            "parserOptions": {
              "project": "./tsconfig.json",
              "tsconfigRootDir": ".",
              "sourceType": "module"
            },
            "plugins": ["@typescript-eslint"],
            "rules": {
              "@typescript-eslint/strict-boolean-expressions": ["error", {
                "allowString": false,
                "allowNumber": false,
                "allowNullableObject": false,
                "allowNullableBoolean": false,
                "allowNullableString": false,
                "allowNullableNumber": false,
                "allowAny": false
              }]
            },
            "ignorePatterns": ["/*", "!/src"]
          }' > .eslintrc.strict.json
          
          echo "With strict config:"
          npx eslint --config .eslintrc.strict.json ./src/components/menus/media/components/helpers.ts || echo "Errors found"
          
      - name: Debug full ESLint run
        run: |
          npx eslint --debug --config .eslintrc.json ./src/components/menus/media/components/helpers.ts 2>&1 | grep -A 10 -B 10 "strict-boolean-expressions" || echo "No matching lines found"